name: tutorial-environment
channels:
  - conda-forge
  - pypi
  - defaults
dependencies:
  - libsndfile
  - ffmpeg
  - jupyter-book
  - jupyterlab
  - numpy
  - matplotlib
  - librosa
  - nussl
  - scaper
  - soxbindings